version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "html-to-pdf-02"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19ozeeqi9133b"
s3_prefix = "html-to-pdf-02"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DomainName=\"pdfshot.dev.db101.org\" Stage=\"Dev\" ZoneId=\"Z00325289ZZE9CCKVUB4\" BucketName=\"html-to-pdf-02-scratch-dev-00\""