AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  html-to-pdf-01

  Sample SAM Template for html-to-pdf-02
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs12.x
    Environment:
      Variables:
        SQS_QUEUE: !Ref SQSQueue
        REGION: !Ref AWS::Region
        SCRATCH_BUCKET: !Ref ScratchBucket

Resources:
  TriggerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: handlers/trigger/
      Handler: index.lambdaHandler
      Timeout: 10
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SQSQueue.QueueName
      Events:
        Trigger:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /html-to-pdf-02
            Method: post
  WorkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/work/
      Handler: index.lambdaHandler
      Timeout: 30
      MemorySize: 1024
      Policies:
        - S3WritePolicy:
            BucketName: !Ref ScratchBucket
      Events:
        SQSTriggerEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSQueue.Arn
            BatchSize: 10
  SQSQueue:
    Type: AWS::SQS::Queue
  ScratchBucket:
    Type: AWS::S3::Bucket

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TriggerApi:
    Description: "API Gateway endpoint URL for Prod stage for trigger function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/html-to-pdf-01/"
  TriggerFunction:
    Description: "Trigger Lambda Function ARN"
    Value: !GetAtt TriggerFunction.Arn
  TriggerFunctionIamRole:
    Description: "Implicit IAM Role created for Trigger function"
    Value: !GetAtt TriggerFunctionRole.Arn
  SQSQueue:
    Description: "SQS Queue URL"
    Value: !GetAtt SQSQueue.Arn
  ScratchBucket:
    Description: "S3 scratch bucket"
    Value: !Ref ScratchBucket