AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  html-to-pdf-02

  Sample SAM Template for html-to-pdf-02
  
Parameters:
  DomainName: 
    Type: String
    Description: Domain name for API
  ZoneId:
    Type: String
    Description: Route53 ZoneId for custom domain
    Default: none
  CertArn:
    Type: String
    Description: Certificate ARN for custom domain. MUST be provisioned on same zone for a regional API.
    Default: none
  Stage:
    Type: String
    Description: Deployment stage
    AllowedValues:
      - Dev
      - Staging
      - Prod
  Version:
    Type: String
    Description: Product version, for use in identifier creation
    Default: '00'
  BucketName:
    Type: String
    Description: Hard-coded bucket name, with reasonable default.

# # This was for an aborted attempt to form the bucket name, which must be lowercase, dynamically. More trouble than it's worth.
# Mappings:
#   Environment:
#     StageLower:
#       Dev: dev
#       Staging: staging
#       Prod: prod

Conditions:
  CreateZone:
    !Equals [!Ref ZoneId, 'none']
  CreateCert:
    !Equals [!Ref CertArn, 'none']

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs12.x
    Environment:
      Variables:
        SQS_QUEUE_IN: !Ref SQSQueueIn
        SQS_QUEUE_OUT: !Ref SQSQueueOut
        REGION: !Ref AWS::Region
        SCRATCH_BUCKET: !Ref ScratchBucket
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  GeneratedZone: # If a Zone ID is not passed in the parameteres, then a new zone is created for the domain
    Type: AWS::Route53::HostedZone
    Condition: CreateZone
    Properties: 
      Name: !Ref DomainName

  GeneratedCert: # If a Certificate ARN is not passed in the parameters, then a new cert is created and will required validation during the deploy
    Type: AWS::CertificateManager::Certificate
    Condition: CreateCert
    Properties: 
      DomainName: !Ref DomainName
      ValidationMethod: DNS

  RestApiGateway:
    Type: AWS::Serverless::Api
    Properties: 
      StageName: !Ref Stage
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !If [CreateCert, !Ref GeneratedCert, !Ref CertArn] 
        Route53:
          HostedZoneId: !If [CreateZone, !Ref GeneratedZone, !Ref ZoneId]

  TriggerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: handlers/trigger/
      Handler: index.lambdaHandler
      Timeout: 10
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SQSQueueIn.QueueName
      Events:
        Trigger:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref RestApiGateway
            Path: /
            Method: post

  WorkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/work/
      Handler: index.lambdaHandler
      Timeout: 30
      MemorySize: 1024
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SQSQueueOut.QueueName
        - S3WritePolicy:
            BucketName: !Ref BucketName
      Events:
        SQSTriggerEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSQueueIn.Arn
            BatchSize: 10

  SQSQueueIn:
    Type: AWS::SQS::Queue

  SQSQueueOut:
    Type: AWS::SQS::Queue

  # # Allow ScratchBucket to send messages to SQSQueueOut
  # SQSQueueOutPolicy:
  #   Type: AWS::SQS::QueuePolicy
  #   Properties:
  #     PolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             AWS: "*"
  #           Action: SQS:SendMessage
  #           Resource: "*"
  #           Condition:
  #             ArnLike:
  #               aws:SourceArn: !Sub 'arn:aws:s3:*:*:${BucketName}'
  #     Queues:
  #       - !Ref SQSQueueOut

  ScratchBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
        - Id: DeleteObsoleteContent
          Prefix: ''
          Status: 'Enabled'
          ExpirationInDays: '7'
      # NotificationConfiguration:
      #   QueueConfigurations:
      #     - Event: 's3:ObjectCreated:*'
      #       Queue: !GetAtt SQSQueueOut.Arn       

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TriggerApi:
    Description: "API Gateway endpoint URL for current stage for trigger function"
    Value: !Sub "https://${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
  TriggerDomain:
    Description: "API Gateway domain as passed to compiler"
    Value: !Sub "https://${DomainName}/"
  TriggerFunction:
    Description: "Trigger Lambda Function ARN"
    Value: !GetAtt TriggerFunction.Arn
  TriggerFunctionIamRole:
    Description: "Implicit IAM Role created for Trigger function"
    Value: !GetAtt TriggerFunctionRole.Arn
  SQSQueueIn:
    Description: "Trigger SQS Queue URL"
    Value: !GetAtt SQSQueueIn.Arn
  SQSQueueOut:
    Description: "Response SQS Queue URL"
    Value: !GetAtt SQSQueueOut.Arn
  ScratchBucket:
    Description: "S3 scratch bucket"
    Value: !Ref ScratchBucket